site_name: "Bao Long"
site_url: "https://baolong1507.github.io/baolong1507/"
theme:
  name: material
  features:
    - toc.follow
    - navigation.top
    - navigation.tracking
  palette:
    - scheme: default

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - def_list
  - footnotes
  - tables

extra_css:
  - stylesheets/extra.css
