site_name: "Bao Long's Homepage"
site_url: "https://baolong1507.github.io/baolong1507/"

theme:
  name: material
  features:
    - navigation.top
    - toc.follow
    - navigation.tracking
  icon:
    logo: fontawesome/solid/graduation-cap

plugins:
  - search

nav:
  - Home: index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css
